### ISSUE TITLE
independent critical exception issue

### ISSUE THREAD

**Issue by jon1enforce** [kashikoibumi/PyBitmessage#8]
2024-06-22 15:21:14,821 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pybitmessage/bitmessageqt/__init__.py", line 4142, in treeWidgetItemClicked
    self.getCurrentSearchOption(), self.getCurrentSearchLine())
  File "/usr/local/lib/python3.7/dist-packages/pybitmessage/bitmessageqt/__init__.py", line 1253, in loadMessagelist
    self.loadSent(tableWidget, account, where, what)
  File "/usr/local/lib/python3.7/dist-packages/pybitmessage/bitmessageqt/__init__.py", line 1234, in loadSent
    self.addMessageListItemSent(tableWidget, *r)
  File "/usr/local/lib/python3.7/dist-packages/pybitmessage/bitmessageqt/__init__.py", line 1176, in addMessageListItemSent
    statusText, False, lastactiontime, ackdata)]
  File "/usr/local/lib/python3.7/dist-packages/pybitmessage/bitmessageqt/foldertree.py", line 482, in __init__
    self.setData(TimestampRole, int(timestamp))
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x02\x01\x01\xfd\xe6\xaad\x17CSO\xac\xc3S\xe9\xd3\x16\\N\xd6wH\xd2\xa0C\xadU\xf8\xfc\x7f\xf3X\r\x90\x08'
2024-06-22 15:22:11,393 - ERROR - 158.69.63.42:8080 error: 2, bytearray(b'Too many connections from your IP. Closing connection.')
2024-06-22 15:22:23,497 - ERROR - 5.135.166.102:8444 error: 2, bytearray(b'Too many connections from your IP. Closing connection.')
2024-06-22 15:23:05,885 - ERROR - 85.114.135.102:8444 error: 2, bytearray(b'Too many connections from your IP. Closing connection.')
2024-06-22 15:23:09,904 - ERROR - 158.69.63.42:8080 error: 2, bytearray(b'Too many connections from your IP. Closing connection.')
2024-06-22 15:24:56,476 - ERROR - Could not determine filesystem type. /home/jon/.config/PyBitmessage/keys.dat

**Comment by jon1enforce** [comment]
on all platforms, freebsd, openbsd, alpine and debian. 
On alpine linux and debian linux -- the connection works -- like send and receive. 
i solved a permission error with adjust udpd.py:


dns 1.1.1.1 or 1.0.0.1 instead of 8.8.8.8.
and port 53 instead of 1500 on udp.
it does not work without udpd.py on alpine linux,yet.

**Comment by kashikoibumi** [comment]
This should be fixed by bdbe5cca616148e3ae3303b7572675d0c96c05b1 .
